title: Arrow Meta
#-------------------------
name: Λrrow Meta
#-------------------------
description: Arrow Meta is the functional companion to the Kotlin Compiler and its plugin ecosystem
#-------------------------
author: The Λrrow Authors
keywords: functional-programming, kotlin-library, monads, monad-transformers, functional-data-structure, kotlin, fp-types, adt, free-monads, tagless-final, mtl, for-comprehension, category-theory
#-------------------------
url: https://arrow-kt.io/docs/meta
#-------------------------
arrow_url: https://arrow-kt.io
#-------------------------
github_repo: https://github.com/arrow-kt/arrow-meta
#-------------------------
twitter_handle: "@arrow_kt"
#-------------------------
slack_kotlin_channel: "https://slack.kotlinlang.org"
slack_arrow_channel: "https://kotlinlang.slack.com/archives/C5UPMM0A0"
#-------------------------
markdown: kramdown
sass:
    style: compressed
#-------------------------
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile', 'build', 'build.gradle.kts', 'gradle.properties']
#-------------------------
defaults:
  - scope:
      path: "apidocs"
      type: "pages"
    values:
      layout: "docs"
