name: Build Documentation

on: pull_request

jobs:
  build_documentation:

    env:
      JAVA_OPTS: -Xms512m -Xmx1024m

    runs-on: ubuntu-latest

    steps:
    - name: Set env
      run: |
        echo "$JAVA_HOME_8_X64/bin" >> $GITHUB_PATH
        echo "JAVA_HOME=$JAVA_HOME_8_X64" >> $GITHUB_ENV
    - uses: actions/checkout@v1
    - name: "Create API Doc and validate"
      run: ./gradlew buildMetaDoc
    - name: "Build"
      env:
        JEKYLL_ENV: production
      run: |
        bundle install --gemfile docs/Gemfile --path vendor/bundle
        BUNDLE_GEMFILE=docs/Gemfile bundle exec jekyll build -s docs/build/site -d docs/build/_site
    - name: "Simulate deploy"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
        AWS_DEFAULT_REGION: eu-west-1
      run: aws s3 sync docs/build/_site s3://$S3_BUCKET --dryrun
