name: Publish Documentation

on:
  push:
    branches:
    - main

jobs:
  publish_documentation:

    env:
      JAVA_OPTS: -Xms512m -Xmx1024m

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '15'
        cache: 'gradle'

    - name: "Create API Doc and validate"
      run: ./gradlew buildMetaDoc

    - name: "Build"
      env:
        JEKYLL_ENV: production
      run: |
        sudo gem install bundler
        bundle install --gemfile docs/Gemfile --path vendor/bundle
        MAYOR_MINOR_VERSION=$(grep -e "^projects.version=.*$" gradle.properties | cut -d= -f2 | cut -d. -f1-2)
        echo $MAYOR_MINOR_VERSION
        # bundle exec jekyll build --baseurl /$MAYOR_MINOR_VERSION -s docs -d docs/build/_site
        BUNDLE_GEMFILE=docs/Gemfile bundle exec jekyll build -b /docs/meta -s docs/build/site -d docs/build/_site

    - name: "Deploy"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        S3_BUCKET: ${{ secrets.S3_BUCKET }}
        AWS_DEFAULT_REGION: eu-west-1
        AWS_CLOUDFRONT_ID: ${{ secrets.AWS_CLOUDFRONT_ID }}
      run: |
        # Waiting for AWS configuration to active this part:
        # aws s3 sync docs/build/_site s3://$S3_BUCKET/$MAYOR_MINOR_VERSION
        aws s3 sync docs/build/_site --delete s3://$S3_BUCKET/docs/meta
        aws cloudfront create-invalidation --distribution-id $AWS_CLOUDFRONT_ID --paths "/*"
